Repository thm-mni-ii/helm-charts, pull requests merged in 2023-01, with the labels that each got.

#3 Init CI/CD
  .github/charts.yml
  .github/release-charts.yml
  README.md
  charts/feedbacksystem/.gitkeep
Labels: CI/CD

#4 ci: move workflows to the correct folder
  .github/workflows/charts.yml
  .github/workflows/release-charts.yml
Labels: CI/CD

#5 [Feedbacksystem] Import fbs chart from main repo
  .ci/update-version.ts
  .github/workflows/charts.yml
  README.md
  charts/feedbacksystem/Chart.lock
  charts/feedbacksystem/Chart.yaml
  charts/feedbacksystem/README.md
  charts/feedbacksystem/generate-values.ts
  charts/feedbacksystem/templates/NOTES.txt
  charts/feedbacksystem/templates/_helpers.tpl
  charts/feedbacksystem/templates/common.yaml
  charts/feedbacksystem/templates/core.yaml
  charts/feedbacksystem/templates/digital-classroom.yaml
  charts/feedbacksystem/templates/mysql-config.yaml
  charts/feedbacksystem/templates/runner.yaml
  charts/feedbacksystem/templates/sql-checker.yaml
  charts/feedbacksystem/values.yaml
  config.yaml
Labels: fbs

#6 ci: use config for chart release
  .github/workflows/release-charts.yml
Labels: CI/CD

#7 fix: replace config with helm repo add and split README.md
  .github/workflows/release-charts.yml
  README.md
  charts/feedbacksystem/README.md
Labels: enhancement
