Repository thm-mni-ii/helm-charts, pull requests merged in 2023-02, with the labels that each got.

#13 Update renovate Configuration
  renovate.json
Labels: CI/CD

#23 [Feedbacksystem] Improve documentation
  README.md
  charts/feedbacksystem/Chart.yaml
  charts/feedbacksystem/README.dev.md
  charts/feedbacksystem/README.md
  charts/feedbacksystem/values.yaml
Labels: documentation, fbs

#25 ci: group all non major dependency updates
  renovate.json
Labels: CI/CD

#27 docs: fix deno argument order
  charts/feedbacksystem/Chart.yaml
  charts/feedbacksystem/README.md
Labels: documentation, fbs

#30 fix(feedbacksystem): disable bin log
  charts/feedbacksystem/Chart.yaml
  charts/feedbacksystem/templates/mysql-config.yaml
Labels: bug, fbs, config

#32 ci(Renovate): Bump github actions only by Tag updates
  renovate.json
Labels: CI/CD

#38 feat(feedbacksystem): add new ldap configuration
  .gitignore
  charts/feedbacksystem/Chart.yaml
  charts/feedbacksystem/README.md
  charts/feedbacksystem/templates/config.yaml
  charts/feedbacksystem/templates/core.yaml
  charts/feedbacksystem/templates/sql-checker.yaml
  charts/feedbacksystem/values.yaml
Labels: fbs, config

#39 docs(feedback): fix --allow-write order
  charts/feedbacksystem/Chart.yaml
  charts/feedbacksystem/README.md
Labels: documentation, fbs

#40 fix(feedbacksystem): fix host helper
  charts/feedbacksystem/Chart.yaml
  charts/feedbacksystem/templates/_helpers.tpl
  charts/feedbacksystem/templates/common.yaml
  charts/feedbacksystem/templates/config.yaml
Labels: fbs, config

#44 feat(feedbacksystem): allow external digital classroom integration
  charts/feedbacksystem/Chart.yaml
  charts/feedbacksystem/README.md
  charts/feedbacksystem/generate-values.ts
  charts/feedbacksystem/templates/_helpers.tpl
  charts/feedbacksystem/templates/core.yaml
  charts/feedbacksystem/templates/digital-classroom.yaml
  charts/feedbacksystem/templates/mysql-config.yaml
  charts/feedbacksystem/values.yaml
Labels: enhancement, fbs
